monai/deploy/core/io_context.py
monai/deploy/core/resource.py
tests/unit/test_runner.py
tests/unit/test_runner_utils.py

The recent `flake8-bugbear` module(21.9.1) introduces additional errors regarding Exception Chaining.
Fix related code to pass flake8 checks.
```
/home/vsts/work/1/s/monai/deploy/core/resource.py:82:17: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling.  See https://docs.python.org/3/tutorial/errors.html#exception-chaining for details.
/home/vsts/work/1/s/monai/deploy/core/resource.py:128:17: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling.  See https://docs.python.org/3/tutorial/errors.html#exception-chaining for details.
/home/vsts/work/1/s/monai/deploy/core/io_context.py:114:17: …
```

Fix flake8 error regarding exception chaining

---

examples/apps/ai_spleen_seg_app/spleen_seg_operator.py
examples/apps/ai_unetr_seg_app/unetr_seg_operator.py
monai/deploy/operators/dicom_seg_writer_operator.py
monai/deploy/operators/monai_seg_inference_operator.py

It is known that the MONAI transform class, `SaveImaged`, uses `np.float32` as the output image data type if none specified.
For segmentation image, the mask image invariantly has `uint8 `for each segment. Furthermore, it has become known that external render programs, e.g. Clara Render Server, assumes `uint8 `segmentation mask image and would fail with other data type.
In addition, the App SDK DICOM Segmentation Writer consumes the in memory segmentation image, and even though `float32` type is handled, it is better to save the image with uint8 for reducing mem usage as well as being consistent.

Segmentation mask image should have uint8 type, for both the saved nii.gz file and in memory Image 

---

monai/deploy/core/domain/dicom_sop_instance.py

Fix dicom dependency by setting the types to Any if pydicom is not available.
Without this patch, it causes the following error when monai-deploy-app-sdk v0.1.0rc1 is installed.
```
---------------------------------------------------------------------------
OptionalImportError                       Traceback (most recent call last)
<ipython-input-1-159a1f2129f7> in <module>()
----> 1 import monai.deploy.core as md
2 from monai.deploy.core import (
3     Application,
4     DataPath,
5     ExecutionContext,
/home/gbae/miniconda3/envs/mednist/lib/python3.6/site-packages/monai/__init__.py in <module>()
41 
42 # load directory modules only, skip loading individual files
---> 43 load_submodules(sys.modules[__name__], False, exclude_pattern=excludes)
44 
45 # load all modules, this will trigger …
```

Fix pydicom dependency

---

examples/apps/ai_spleen_seg_app/app.py
examples/apps/ai_unetr_seg_app/app.py

It is an oversight that in the derived Application classes, the run() method shadows the base run, and as such, does not support args.
It is also true that the run() function in the derived class does not add any logic except logging statements, though keeping it in the derived class is fine too.

Derived app class needs to support args and kwargs in the run function.

---

.bumpversion.cfg
docs/source/getting_started/installing_app_sdk.md
monai/deploy/runner/runner.py
monai/deploy/runner/utils.py

- Use POSIX path for App Runner 
- Do not use shlex.quote for Windows
- Update .bumpversion.cfg to sign-off commit 
- Bump version to `0.1.1rc2 `
Created `0.1.1rc2` package on test PyPI for test.
```bash
pip install -i https://test.pypi.org/simple/ monai-deploy-app-sdk==0.1.1rc2
```
resolve #152

Use POSIX path for App Runner to handle Windows path

---

monai/deploy/packager/util.py
monai/deploy/runner/runner.py

MAP is created with the default UID/GID (1000) by default.
However, if the user has UID which is not 1000 such as 1001, the local input/output folder is mounted with the host's input folder permission (1001) by App Runner and causes the following message when MAP is executed.
```bash
...
Reading MONAI App Package manifest...
> export '/var/run/monai/export/' detected
fatal: Access to the path '/var/run/monai/export/config/pkg.json' is denied.
ERROR: Failed to fetch MAP manifest.
Execution Aborted
```
This patch builds a Docker image with local UID/GID to resolve the issue.
Also, it retrieves app/package information with the faster method if the OS is not Windows.
(copying app.json/pkg.json through `docker cp` command is faster than launching container to download config file).
```python …
```

Build package with local UID/GID and fast-retrieve app/package information

---

docs/source/release_notes/index.md
docs/source/release_notes/v0.2.0.md
examples/apps/mednist_classifier_monaideploy/mednist_classifier_monaideploy.py
monai/deploy/core/domain/dicom_sop_instance.py
monai/deploy/operators/__init__.py
monai/deploy/operators/dicom_data_loader_operator.py
monai/deploy/operators/dicom_seg_writer_operator.py
monai/deploy/operators/dicom_series_selector_operator.py
monai/deploy/operators/dicom_series_to_volume_operator.py
monai/deploy/operators/dicom_text_sr_writer_operator.py

This PR intends to add the DICOM text SR related assets as well as updating operator test functions,
- add the Modelnfo class to encapsulate AI model info, per IHE AI Results (AIR) Rev 1.1, to be instantiated by the app.
- add the EquipmentInfo class to encapsulate the DICOM instance equipment module, to be instantiated by the app.
- add static function, write_common_modules, to writer common DICOM modules for all AI result instances.
- Note the above 3 will be moved into Domain module, but for now, in the dicom_text_sr_writer_operator module.
- Created dicom_text_sr_writer_operator, to accept AI textual results (classification results) and generated DICOM 3D SR instance.
- Provided support for copying over tags from input DICOMSeries, as well as generating tags anew in the case of no …

Added DICOM text SR assets and updated all operator test functions.

---

.bumpversion.cfg
docs/source/developing_with_sdk/deploying_to_the_remote_server.md
docs/source/getting_started/tutorials/04_mis_tutorial.md
docs/source/getting_started/tutorials/05_full_tutorial.md
docs/source/getting_started/tutorials/index.md
docs/source/release_notes/index.md

- Release current origin/main as v0.2.0 (tagging `0.2.0`)
- Create `v0.2` and `v0.2.0` branches for tracking the version.
- Create a tag 0.2.0 for v0.2.0
Doc: https://docs.monai.io/projects/monai-deploy-app-sdk/en/0.2.0/
v0.2.0 has the following changes, compared with v0.1.1
- #203
- #167
- #201
- #168
- #200

Release v0.2.0

---

examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
examples/apps/ai_spleen_seg_app/spleen_seg_operator.py
examples/apps/ai_unetr_seg_app/unetr_seg_operator.py
examples/apps/deply_app_on_aarch64_interim.md
monai/deploy/operators/monai_seg_inference_operator.py
notebooks/tutorials/03_segmentation_app.ipynb
notebooks/tutorials/05_full_tutorial.ipynb

It was found out that when running Jupyter-lab within a environment set up using conda, pytorch encountered error related to MKL, see [pytorch issue](https://github.com/pytorch/pytorch/issues/37377).
A previous [PR ](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/208) modified the Jupyter notebook adding env var ['MKL_THREADING_LAYER'] = 'GNU' to work around the MKL issue, which is one of the suggested fixes.
A cleaner fix, as also [stated in the said issue](https://github.com/pytorch/pytorch/issues/37377#issuecomment-807271090), is to upgrade to numpy 1.20 to avoid the MKL issue without needing the env var workaround.
The example segmentation examples had already been tested with numpy >= 1.20, so it is the safe and correct fix to bump the numpy version >= 1.20, in the apps, …

Bump numpy >= 1.20 to avoid MKL error in conda env, and add --upgrade for pip install app sdk

---

docs/source/getting_started/tutorials/03_segmentation_app.md
notebooks/tutorials/03_segmentation_app.ipynb
notebooks/tutorials/04_mis_tutorial.ipynb
notebooks/tutorials/05_full_tutorial.ipynb

This is to avoid confusion as the .pt and .ts are used by some model sources to distinguish PyTorch and TorchScript model files, e.g. Clara MMAR.
A new dataset zip file has been uploaded to Google drive, and the Jupyter notebooks in the tutorials have been updated to download the new zip file and use the updated model file name. The original dataset zip file is still available on the Google drive, in case existing version of the Spleen Seg Jupyter notebook is used.
Noted again that Jupyter notebooks 04 and 05 copied some steps from the Spleen Seg; the duplication inevitably causes duplicated effort when the source changes.      

Change the model name in the Spleen seg example dataset to model.ts

---

docs/source/conf.py
docs/source/index.md
docs/source/modules/index.md
monai/deploy/cli/exec_command.py
monai/deploy/packager/package_command.py
monai/deploy/runner/run_command.py
run

Fixed empty documentation on docs.monai

---

monai/deploy/core/application.py
monai/deploy/utils/importutil.py

To detect if the code is run inside Jupyter notebook (IPython) or not, it tried to find whether the class's file name starts with `<ipython-` or not.
Meanwhile the approach worked on Google Colab and some Jupyter Notebook versions. There were some cases where the class's file name is like `/tmp/ipykernel_xxxxx/xxxxxxxxx.py` causing the failure described in #206.
This patch uses a different approach.
If the file path is not available, it tries to see each frame information in the stack to check whether the file name ends with "interactiveshell.py" and the function name is "run_code".
If so, it returns `Path("ipython")` to notify that the class is defined inside IPython.
Fixes #206

Fix IPython detection routine

---

monai/deploy/operators/dicom_series_to_volume_operator.py

Per Issue [#187](https://github.com/Project-MONAI/monai-deploy-app-sdk/issues/187), added exception handling when parsing Rescale Intercept (0028,1052) and Rescale Slope (0028,1053).
- Rescale Intercept (0028,1052) is of Type 1C. It is required if Modality LUT Sequence (0028,3000) is not present, and shall not be present otherwise.
- Rescale Slope (0028,1053) is also Type 1C, required if Rescale Intercept is present. 
- Rescale Type (0028, 1054) is not parsed or used in the implementation as of now. This attribute is required if Rescale Intercept is present.
These attributes have been observed missing, even in the absence of LUT, in DICOM instances generated with open source utility tools that converts NIfTI image to DICOM. It is safe to use 0 and 1 for the intercept and slope to handle …

Handle exception case with missing DICOM Rescale Intercept and Slope attributes

---

monai/deploy/operators/monai_seg_inference_operator.py

If the user's application doesn't depend on `monai` and monai is not installed, it causes an error when the following statement is executed by the interpreter.
https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/eebb284d3130e122f933f5241509d0a438699d9d/monai/deploy/operators/monai_seg_inference_operator.py#L239
This patch sets `ImageReader` to `object` if `monai` library is not available so the user's app doesn't require `monai` app if not using.

Make InMemImageReader work even when monai is not used/available

---

docs/source/getting_started/tutorials/01_simple_app.md
docs/source/getting_started/tutorials/02_mednist_app.md
docs/source/getting_started/tutorials/03_segmentation_app.md

[JupyterLab dropped its support for Python 3.6](https://github.com/jupyterlab/jupyterlab/pull/11740) 
(Jupyter notebook still works on Python 3.6).
- https://github.com/jupyterlab/jupyterlab/pull/11740
- https://github.com/jupyter/notebook/blob/master/notebook/traittypes.py#L17
- https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/traittypes.py#L7
Update document to use Python 3.7 for JupyterLab.
Fixes #240

Use Python 3.7 for JupyterLab

---

monai/deploy/packager/templates.py
monai/deploy/packager/util.py

Removing fixed `monai` user/privilege's on application package image

Remove MONAI user ownership on MAP folders

---

monai/deploy/packager/templates.py

By default, app packager is using `nvcr.io/nvidia/pytorch:21.07-py3` as a base image and the image already has PyTorch that were manually compiled by NVIDIA to support latest architectures such as Amphere.
- https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
Since `--upgrade` was used in `pip` command to install necessary packages, `pytorch` is upgraded but with wring configuration (1.10.1+cu102) when installing PyTorch requires [additional instructions](https://pytorch.org/get-started/locally/) for installation.
This patch removes the option when installing packages so that already-installed packages does not upgrade unless needed.

Do not upgrade packages when packaging

---

.github/workflows/pr.yml
.readthedocs.yml
docs/source/getting_started/installing_app_sdk.md
docs/source/getting_started/tutorials/01_simple_app.md
docs/srs.md
pyproject.toml
setup.cfg

As per MONAI Core's [Python 3.6 drop](https://github.com/Project-MONAI/MONAI/pull/3536), drop the support for Python 3.6 from MONAI Deploy App SDK.

Drop Python 3.6 support

---

monai/deploy/operators/dicom_series_to_volume_operator.py
monai/deploy/operators/monai_seg_inference_operator.py

The noted issue in the generated DICOM Seg instance will be investigated outside of this PR.
The Image object instances in the application pipeline was not completely consistent in its representation of the pixel in NumPy array, especial around the index order, i.e. DWH or DHW. One wonders if the representation is similar to what's provided in other packages, e.g. (Simple) ITK.
This PR intends to make the App SDK Image object instances in the processing pipeline of an application more consistent by separating the concerns during image loading of DICOM instance, during inference using MONAI transforms including re-shaping the image array, and the output Image after inference:
1. Consistent with ITK on converting DICOM series instances to volumetric image in DICOMSeriesToVolumeOperator. The …

Make DICOMSeriesToVolumeOperator consistent with ITK in serving NumPy array

---

monai/deploy/operators/png_converter_operator.py

The Image object that is created by the DICOM to Image converter now contains a numpy array with index order of DHW, the same way as ITK does. So, the depth (slicing along this axis for the original DICOM slice) is now the first dim, and the indexing needs to change accordingly.

Updated the png converter operator following changes to Image ndarray index order.

---

monai/deploy/operators/dicom_data_loader_operator.py

It has been found that this loader is overly restrictive in that it expects a folder containing only valid DCIOM part 10 files.
So, this PR is to
- relax the limitation by skipping non-DICOM files
- maintain input processing validation by giving the user/application the control and option to raise error if no DICOM studies are loaded. This will stop the processing at this data loading stage if downstream processing needs valid loaded data objects.

Relaxed the restriction on non-DCM files, and raise error based on settings

---

monai/deploy/operators/dicom_data_loader_operator.py
monai/deploy/operators/dicom_seg_writer_operator.py
monai/deploy/operators/dicom_series_selector_operator.py
monai/deploy/operators/dicom_series_to_volume_operator.py
monai/deploy/operators/dicom_text_sr_writer_operator.py
monai/deploy/operators/inference_operator.py
monai/deploy/operators/monai_seg_inference_operator.py
monai/deploy/operators/png_converter_operator.py
monai/deploy/operators/stl_conversion_operator.py
notebooks/tutorials/03_segmentation_app.ipynb
notebooks/tutorials/03_segmentation_viz_app.ipynb
notebooks/tutorials/05_full_tutorial.ipynb

We are working on a large dataset of single frame 2D x-ray images (DICOMs). Some of these images lack the DICOM tag "Pixel Spacing" (0028, 0030) resulting in a KeyError in DICOMDataLoaderOperator.
For some x-ray images (of our dataset but also in general) pixel spacing can only be stored in the DICOM tag "Imager Pixel Spacing" (0018, 1164). This PR adds code to cover this use case.

Fix pixel spacing in DICOMDataLoaderOperator for some X-rays

---

examples/apps/ai_livertumor_seg_app/app.py
examples/apps/ai_unetr_seg_app/app.py
monai/deploy/operators/dicom_seg_writer_operator.py

Investigated this issue from multiple angles, but as often the case, an unexplainable change cause the issue:
-  In the original check-in on 08/24/2021 works (the core impl is based on existing working version). The Segmentation type is a binary seg, so Line 486: `dicomOutput.BitsAllocated = 1` 
- Later, on 09/17/2021, for unknown reason, bit allocated was changed, Line 524: `dicomOutput.BitsAllocated = 8`
- The fix is then simply reverting the bits allocated back to 1, testing the DICOM Seg Writer by itself, and then testing the applications that use the DICOM Seg Writer. The results were verified.
- Also noted that the DICOM Seg Writer can only support up to 8 segmentation labels, and this is the reason the UNETR example application fails to create DICOM Seg instance as it has upto 13 …

Fix issue245 DICOM Seg has multiple slices of seg image on the same frame 

---

monai/deploy/operators/dicom_data_loader_operator.py
monai/deploy/operators/dicom_series_to_volume_operator.py

Apply the "INVERSE" for pixel array with Phohometic Interpretation of MONOCHROME1/INVERSE, so that the minimum value is black, similar to MONOCHROME2/IDENTITY, during series to volume image conversion.
@jlvahldiek this is similar to what is in your aborted PR, but I have not compared the performance yet. Please review this PR. 
Note there are more enhancements needed, to come, e.g. considering the LUT, and compressed pixel data.

Add support for MONOCHROME1

---

monai/deploy/packager/util.py
monai/deploy/runner/runner.py

Add a simple change to log execution command when log level is `DEBUG`
```bash
monai-deploy package apps/simple_imaging_app -t simple_app:latest -l DEBUG         
```
```
[DEBUG] (app_packager) - Docker image build command: docker build -f "./monai_tmprxl05_xh/dockerfile" -t simple_app:latest "./monai_tmprxl05_xh" --build-arg MONAI_UID=$(id -u) --build-arg MONAI_GID=$(id -g)
```
```bash
monai-deploy run simple_app:latest input output output -l DEBUG           
```
```
...
Executing command: docker run --rm -a STDERR -a STDOUT -e MONAI_INPUTPATH="/var/monai/input" -e MONAI_OUTPUTPATH="/var/monai/output" -e MONAI_MODELPATH=/opt/monai/models -v "/home/gbae/repo/monai-deploy-app-sdk/examples/input":"/var/monai/input" -v "/home/gbae/repo/monai-deploy-app-sdk/examples/output":"/var/monai/output" …
```

Add debug message for App packager/runner command

---

monai/deploy/core/executors/single_process_executor.py

Existing description for SingleProcessExecutor.run() method is wrong.
This patch describes the correct behavior of the method.

Fix the description of SingleProcessExecutor.run() method

---

docs/source/getting_started/tutorials/06_monai_bundle_app.md

The content file in MD in the getting_started/tutorials for the newly added Jupyter Notebook on MONAI Bundle missed the boat, so needs to be added and cherry-pick to v0.4.0 branch.

Add the missing content file

---

.bumpversion.cfg
docs/source/getting_started/tutorials/06_monai_bundle_app.md
docs/source/release_notes/index.md
docs/source/release_notes/v0.4.0.md

- New operator to automate inference with the newly introduced [MONAI Bundle](https://docs.monai.io/en/stable/whatsnew_0_9.html)
The new operator, `MONAI Bundle Inference Operator`, is intended to automate the inference with a MONAI Bundle in TorchScript with the following functionalities:
- Parse the model metadata and extra configuration data in the TorchScript file
- Instanciate MONAI transforms and inferer objects per bundle configuration data
- Convert input/output of the operator to and from model network input
- Support named model and can be used in a multi-model application
The example [spleen segmentation application](https://github.com/Project-MONAI/monai-deploy-app-sdk/tree/main/examples/apps/ai_spleen_seg_app) was accordingly updated to demonstrate the use of this new …

Release v0.4.0

---

README.md

This is a a bit of a chicken-and-egg problem, since the readme.md refers
to the published latest version of the doc which can only happen when
the release build is done, and this particular doc is part of the build,
included in the package to be pushed to pypi.org.
Next time, need to consider add the entry, with a placeholder/non-existent
URL prior to the release build, so that the content will show up in the new
package, and URL leads to valid content post build.

Add the newly introduced example to readme.md

---

examples/apps/ai_livertumor_seg_app/app.py
examples/apps/ai_spleen_seg_app/app.py
examples/apps/ai_unetr_seg_app/app.py
monai/deploy/operators/dicom_seg_writer_operator.py
monai/deploy/operators/monai_bundle_inference_operator.py
monai/deploy/operators/monai_seg_inference_operator.py
requirements-dev.txt
requirements-examples.txt

I am recreating this pull request since I completely borked #298 due to the (extremely frustrating) DCO sign off requirement and subsequent attempts to fix it that made it worse :persevere: 
This PR introduces the highdicom library to handle the creation of DICOM segmentations. This should lead to more maintainable code by using the well-tested highdicom package for the complex task of segmentation creation, and should make adding new features to the segmentation writer operator considerably easier by leveraging the prior work in that library. Note that the complexity of the ad-hoc code in the dicom segmentation operator file is reduced significantly.
Unlike the original version of #298 I have now removed the highdicom class `highdicom.seg.SegmentDescription` from the public API of the …

Implement highdicom seg operator

---

monai/deploy/operators/monai_bundle_inference_operator.py

Per discussion in issue/bug #326 , this PR is to fix the missing value on setting the init state. The impact to the app execution is minimal, if any, in the example apps.

Fix the setting of init state in its own PR, instead of rolled into others

---

THIRD_PARTY_NOTICES/highdicom_MIT_LICENSE.txt

The App SDK acknowledges 3rd party dependencies by listing their published license files in the Third Party Notices folder, so that the users of the App SDK can ensure the legality of adopting App SDK for intended uses.

Add highdicom license to the Third Party Notices

---

examples/apps/ai_unetr_seg_app/__main__.py
examples/apps/ai_unetr_seg_app/app.py
monai/deploy/operators/stl_conversion_operator.py
setup.cfg

In this PR, the STL Conversion has been improved
- execution of `compute` will not affect the the object state, and only input data will be transformed to be the output
- Fix the output to be in_memory STL binary in a try/catch block, so this output will only be available when the operator is a non-leaf node (current limitation on output mapping)
- STL file is only saved in the app's output folder, if and only if a file path is provided, which is stored as operator private attribute
Changes are also made to the unetr example to demonstrate reusing the same app obj for processing multiple/batch of inputs,
- `__main__` functions have been updated to process a set of subfolders under the app input folder, each containing a DICOM Study/series, to demonstrate batch processing. Example code can …

Improve STL operator so the enclosing app obj can run repetitively

---

examples/apps/ai_livertumor_seg_app/app.py
examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
monai/deploy/operators/dicom_series_selector_operator.py
setup.cfg

Existing series selection implementation supports matching attributes at down to series level, however, sometimes key instance level attributes can help narrow down the selection, e.g. `Photometric Interpretation`.
Also updated the example app for make use of the updated selector, as well as pinning the monai dependency at 0.9.0 for now.
Signed-off-by: M Q <mingmelvinq@nvidia.com>

Added support of matching instance level tags, and update liver seg

---

integrations/nuance_pin/app/inference.py
integrations/nuance_pin/app/post_inference_ops.py

- Change the HU window size for GSPS objects
- Fix spacing so it's resilient to more inputs

Nuance pin integration minor adjustments

---

examples/apps/ai_livertumor_seg_app/app.py
examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
monai/deploy/operators/dicom_series_selector_operator.py
monai/deploy/operators/dicom_text_sr_writer_operator.py
setup.cfg

This pull request intends to merge some changes made during the IHE Connectathon IAIP testing.
- Update the series selection operator to support matching DICOM instance level metadata
- Updated the liver tumor segmentation example to include simple filtering rules
- Updated the text SR writer to add time zone offset from UTC, while keep content date time local
- Updated the text SR writer to use content sequence for sections of text
- Updated the text SR writer storage SOP class to that of basic text SR

Enhance some attributes in the text SR writer

---

THIRD_PARTY_NOTICES/PyPDF2_BSD-3_LICENSE.txt
examples/apps/mednist_classifier_monaideploy/mednist_classifier_monaideploy.py
monai/deploy/operators/__init__.py
monai/deploy/operators/dicom_encapsulated_pdf_writer_operator.py
monai/deploy/operators/dicom_text_sr_writer_operator.py
monai/deploy/operators/dicom_utils.py

This PR is to:
- split from the existing text SR writer the dicom_utils module for reusable classes and function, e.g. equipment info, model info, DICOM common module writer for study, patient, SOP commons, etc.
- the DICOM Text Writer becomes much smaller and clearer to read
- the DICOM Encapsulated PDF write is added with minimal amount of code. This new writer take in either PDF bytes or a file path to load byte from, optionally with a DICOM Series for copying study level tags, and writes the DICOM Encapsulated PDF instance file. The loaded PDF in bytes are validated for being PDF with the use of PyPDF2  
- the app that uses the Text SR writer, mednist classification, is updated with simple change. This app is also used as the tester, even though the writers have test function for …

Add DICOM PDF Writer and split dicom_utils common module out of Text SR Writer

---

monai/deploy/operators/dicom_series_selector_operator.py

This PR enhances the code to treat multi-value DataElement retrieved from SOP instance Dataset differently from single valued ones.
DataElement retrieved from the underlying SOP instance Dataset may be multiple-valued; the retrieval is only needed when the to-be-matched attribute is not in the defined set of study and series attributes and when instance level attributes are used. The existing implementation favors multiple-valued and converts the string representation of the multi-valued into a list, however this also makes a single value into a list which then causes issue when valuating the condition.
Signed-off-by: M Q <mingmelvinq@nvidia.com>

Enhanced multi-value DataElement parsing

---

examples/apps/ai_spleen_seg_app/app.py
monai/deploy/operators/monai_bundle_inference_operator.py

Per bug report, the Config Parser needs to parse the full list of configs all at once.
- As before, try to avoid extracting files to tmp dir, so if only one item is needed, directly read from the archive (into bytes). The helper function to extract content directly from a single file in the archive has been enhanced to try both supported file types, e.g. .json and .yaml.
- When list of config (files) are need to be parsed
- considered using mem mapped files to hole content retrieved from the archive, however, the underlying config parser function, load_config_file, does not support mmap type
- have to use tempfile.TemporaryDirectory as destination for extracting only the files for the named configs, both .json and .ymal will be tried, first match wins
- Tested with sample app which was …

Enhanced code to extract and parse specific config files from TorchScript archive

---

examples/apps/breast_density_classifer_app/README.md
examples/apps/breast_density_classifer_app/__init__.py
examples/apps/breast_density_classifer_app/__main__.py
examples/apps/breast_density_classifer_app/app.py
examples/apps/breast_density_classifer_app/breast_density_classifier_operator.py

This MAP takes a breast study and creates dicomSR as output. The MAP is based on the [breast density model](https://github.com/Project-MONAI/model-zoo/tree/dev/models/breast_density_classification) in the model zoo. 
Please review.

A breast density monai application package

---

monai/deploy/operators/__init__.py
monai/deploy/operators/nii_data_loader_operator.py

Signed-off-by: gupta <gupta@DIGI1036734.mayo.edu>

Added a Nifti data loader for issue #270

---

monai/deploy/operators/nii_data_loader_operator.py

This quick fix is needed to avoid MAP container runtime errors by using optional import on packages that are used by an App SDK built-in operator but not all application.
Also the dependent package needs to be stated in the operator's decorator so that this dependency is collected and become part of the requirements file when building MAP container image.
Signed-off-by: M Q <mingmelvinq@nvidia.com>

Quick fix to avoid package not found error by use optional import

---

.github/workflows/pr.yml

Re-writes version numbers as strings rather than as numbers in `.github/workflows/*.yml` files because 3.1 != 3.10, etc.  Nothing is broken at present but in the future as, e.g., a Python version goes from 3.8 to 3.9 to 3.10, this could end up being an unexpected problem.
Signed-off-by: Lee Newberg <lee.newberg@kitware.com>

ENH: Versions as strings, not numbers, so that 3.1 != 3.10, etc.

---

examples/apps/breast_density_classifer_app/app.py

Needed to provided this fix after building and testing MAP of the breast density classification app
- Somehow highdicom dependency is dragged in. Add this package in the App pip_packages decorator to avoid runtime error.
- Need to change the app.py __main__ function to directly init and run the app object, because the packager sets the command to run app.py instead of app/. Need to rename the original main() which served as test function to test()
- Published the MAP on ghcr.io, http://ghcr.io/mmelqin/monai_ai_breast_density_cls_app:1.0, to be used as a candidate in the AWS Imaging Service integration demo
Signed-off-by: M Q <mingmelvinq@nvidia.com>

Fix runtime error for MAP of breast density classification app

---

monai/deploy/operators/dicom_seg_writer_operator.py

As discussed in the working group, expose the option to set `omit_empty_frames` to `False` in the dicom segmentation writer operator to workaround issues with some viewers (e.g. OHIF).
Addresses #397 @hossam99-9 @GreySeaWolf

Expose option to omit empty frames

---

examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
examples/apps/ai_unetr_seg_app/unetr_seg_operator.py
monai/deploy/core/application.py
monai/deploy/core/executors/single_process_executor.py
monai/deploy/core/graphs/nx_digraph.py
monai/deploy/operators/dicom_data_loader_operator.py
monai/deploy/operators/dicom_encapsulated_pdf_writer_operator.py
monai/deploy/operators/dicom_seg_writer_operator.py
monai/deploy/operators/dicom_series_to_volume_operator.py
monai/deploy/operators/dicom_text_sr_writer_operator.py
monai/deploy/operators/dicom_utils.py
monai/deploy/operators/monai_bundle_inference_operator.py
monai/deploy/utils/importutil.py
notebooks/tutorials/02_mednist_app-prebuilt.ipynb
notebooks/tutorials/03_segmentation_app.ipynb
notebooks/tutorials/03_segmentation_viz_app.ipynb
notebooks/tutorials/06_monai_bundle_app.ipynb
notebooks/tutorials/07_multi_model_app.ipynb
platforms/nuance_pin/app/inference.py
platforms/nuance_pin/app/post_inference_ops.py
platforms/nuance_pin/app_wrapper.py
pyproject.toml
requirements.txt
run
setup.cfg

This PR is intended to only change the version of typeguard to ~=2.12.1 (which is equivalent "typeguard>=2.12.1, <3") in the requirements file as well as the Jupyter Notebooks, as it had been discovered that the newer v3 caused application runtime issues when validating the IO_context. Limiting the typeguard version to below 3 avoids the false error, and is used as the solution for the time being while the App SDK is migrated.
However, more files had to be updated, not related to the intended changes but more to resolve the complaints from the newer versions of Flake8, pytype, and mypy,
- the existing setup.cfg is not compatible with the latest pytype, v2023.03.13, with one symptom being the inputs could not be parsed out by pytype. So, new config was regenerated and added to …

Fix issue 410 where the latest typeguard version 3.x is incompatible

---

monai/deploy/utils/importutil.py

A fix to handle a change in python 3.10 for the inspect.getfile function. It now returns an `OSError: source code not available`

Fixes Project-MONAI/monai-deploy-app-sdk#433

---

examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
monai/deploy/operators/monai_seg_inference_operator.py

Added an option for SimpleInferer on monai_seg_inference_operator.py

Added option for SimpleInferer 

---

.readthedocs.yml

`stable` image doesn't support Python 3.8, causing the following issue.
```
Problem in your project's configuration. Invalid "python.version": expected one of (2, 2.7, 3, 3.5, 3.6, 3.7, pypy3.5), got 3.8
```
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image-legacy
And looks like we are using the old configuration.
This PR updates the configuration to use the latest syntax.

Update Read The Docs configuration to support Python 3.8

---

.bumpversion.cfg
docs/source/getting_started/installing_app_sdk.md
docs/source/getting_started/tutorials/mednist_app.md
docs/source/getting_started/tutorials/monai_bundle_app.md
docs/source/getting_started/tutorials/segmentation_app.md
docs/source/getting_started/tutorials/segmentation_clara-viz_app.md
docs/source/getting_started/tutorials/simple_app.md
docs/source/release_notes/index.md
docs/source/release_notes/v0.5.1.md

Some error happened during releasing v0.5.1, so the release note and related doc changes did not get committed back to main, and the v0.5 is one commit ahead of main.
This one is intended to cherry-pick the last commit back to main.

WIP: merge the missed "Bump version: 0.5.0 → 0.5.1" changes to main from v0.5

---

docs/requirements.txt
docs/source/conf.py
run

It has been observed that gen doc takes a very long time to install multiple versions of nbformat, both locally and on readthedocs, on the latter the [build fails](https://readthedocs.org/projects/monai-deploy-app-sdk/builds/24041688/) due to 30 mins timeout.
It has been identified that the older the few Jupyter notebook related packages, with their older version for Python 3.8, strangely caused multiple versions of nbformat to be installed.
Removing the most Jupyter notebook related packages, except for myst-nb with newer version, reduced the gen doc time dramatically.  
Removing App Sdk, example app and jupyter notebook requirments also further reduced the doc build time and has no impact on final doc.

Fixing the now extreme long time to pip install during gen doc, causing timeout failure on readthedoc

---

docs/source/getting_started/tutorials/simple_app.md

Adding the missed step for setting input env var to fix the issue when running the example simple imaging app in the tutorials.

Adding missed steps to fix issue in the tutorial for simple imaging app

---

monai/deploy/operators/dicom_data_loader_operator.py

Will flesh out comment more tomorrow, just wanted to get some preliminary notes down prior to tomorrow's meeting.
Solution stores each SOP instance in a new dictionary (not ideal) and checks if the combination of `StudyInstanceUID`, `SeriesInstanceUID`, and `ImagePositionPatient` has been seen before; if so, it removes the duplicate, with preference for the higher `AcquisitionNumber`. In cases where the `ImagePositionPatient` tag is not present (X-Ray images, some non-image DICOM files like SR, KO, PR, etc. modalities), no duplication check takes place. This approach is effective for handling the case discussed:
```bash
[2025-04-15 23:07:39,429] [INFO] (dicom_data_loader_operator.DICOMDataLoaderOperator) - No or invalid input path from the optional input port: None
[2025-04-15 …
```

Duplicate Input DICOM Spatial Coordinates

---

monai/deploy/operators/dicom_seg_writer_operator.py

From Contributing Equipment Sequence for DICOM SEG Writer [discussion](https://github.com/Project-MONAI/monai-deploy-app-sdk/discussions/528). `DICOMSegmentationWriterOperator` updates to align with the other DICOM writer operators and the [IHE Radiology AI Results](https://www.ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_Suppl_AIR.pdf) criteria.
This initial commit adds `model_info` as an optional parameter to the `DICOMSegmentationWriterOperator`, allowing for the `ContributingEquipmentSequence` nesting in the DICOM SEG output:
```python
my_model_info = ModelInfo(
creator="CCHMC CAIIR", # institution name
name=_algorithm_name, # algorithm name
version=_algorithm_version, # algorithm version
uid="0.0.1", # MAP version
)
```
@MMelQin, a few thoughts for you after this initial commit: …

DICOM Seg Writer Op Tag Writing Updates

---

monai/deploy/operators/dicom_series_to_volume_operator.py

The array was being read in as int16 which caused some values to be truncated, it should instead be uint16. I also added a check that uint16 is sufficient after the slope/intercept transformation is applied. if it is not, it will use int32 instead.

Fix DICOMSeriesToVolumeOperator casting bug

---

monai/deploy/operators/dicom_series_to_volume_operator.py

Fixed a typo in the last merge and formatting complaints.

The tag value for usinged int is 0

---

monai/deploy/operators/dicom_series_selector_operator.py

Following some requests from clinicians at CCHMC with regards to series selection, the following updates have been made to the `DICOMSeriesSelectorOperator`:
- Matching of image orientation using the `ImageOrientationPatient` tag; the row and column cosines are used to compute the image orientation, which can be matched as Axial, Coronal, or Sagittal; logic is contained in the `_match_image_orientation` helper method
- Relational operator (`>`, `>=`, `<`, `<=`, `!=`) matching for numerical DICOM tags; previously, the only relational operator supported was for exact matching (`==`)
Additionally, the following cleanup was performed:
- Consolidation of all numerical DICOM tag matching logic to the `_match_numeric_condition` helper method
- Updated some logging to be more descriptive and …

DICOMSeriesSelectorOperator Improvements

---

monai/deploy/core/models/torch_model.py

- Updated copyright notice to reflect the years 2021-2025.
- Enhanced the logic for identifying TorchScript models by clarifying the required files and directories in the zip archive format.
Address #544

Improve TorchScript model identification logic in torch_model.py

---

monai/deploy/core/__init__.py
monai/deploy/operators/monai_seg_inference_operator.py

When translating the [MONAI CT TotalSegmentator MONAI Bundle](https://github.com/Project-MONAI/model-zoo/tree/dev/models/wholeBody_ct_segmentation) to a MAP, it was determined that the segmentations produced by the MONAI Bundle and MAP were not exactly aligned (i.e. DICE != 1 for all organs).
This seems to be due to the `MONAISegInferenceOperator` not accepting all the possible arguments that are accepted by the [sliding_window_inference](https://github.com/Project-MONAI/MONAI/blob/d388d1c6fec8cb3a0eebee5b5a0b9776ca59ca83/monai/inferers/utils.py#L42) method, specifically `mode` and `padding_mode` for this Bundle. Once a custom operator that accepted these input arguments was implemented into the MAP pipeline, the DICE for all organs was ~=0.99 when comparing to the Bundle.
This initial …

MONAISegInferenceOperator Additional Arguments

---

examples/apps/ai_multi_ai_app/requirements.txt
examples/apps/ai_spleen_seg_app/requirements.txt
notebooks/tutorials/03_segmentation_app.ipynb
notebooks/tutorials/03_segmentation_viz_app.ipynb
notebooks/tutorials/04_monai_bundle_app.ipynb
notebooks/tutorials/05_multi_model_app.ipynb
requirements-dev.txt
requirements-examples.txt

Pin monai<=1.5.0 per issue #557

Pin monai<=1.5.0 before compatibility issues with 1.5.1 is addressed
